### ISSUE TITLE
battery life

### ISSUE THREAD

**Issue by lclem** [mattpassarelli/diy-smart-door#1]
hello, how long does the battery last when the system is idle?
i.e., are we talking about on the order of 1 day, 1 week, or 1 month?

**Comment by mattpassarelli** [comment]
I moved at the start of the year and haven't used it since, so it's been a while. But nothing some simple math can't tell us! You can estimate how long something will last off battery power by doing (capacity of the battery in mAh)/(the power draw of your device in mA). Obviously power draw will vary based on different factors like if you use a different board or how often the servo spins. 

But for this specific board and now including any servos, we can do 4400mAH (the size of battery I used)/~50mA (based on this power draw chart here https://bbs.espressif.com/viewtopic.php?t=133). Since the code I wrote has the device constantly looking to a REST server for commands, it never really gets a chance to enter sleep; a good place for optimization. But that exact configuration should give you about ~88 hours of constant on time, give or take the factors mentioned above.
